### ISSUE TITLE
RAS MCAT Ping Fails on Restricted S3 Bucket

### ISSUE THREAD

**Issue by ShaneMPutnam** [USACE/mcat-ras#2]
The RAS MCAT ping request fails when pinging an S3 bucket with restricted permissions, even if the user is able to access keys within that bucket and everything else is working correctly.

**Comment by albrazeau** [comment]
Can you check what the error message is [here](https://github.com/USACE/mcat-ras/blob/feature/refactor/handlers/ping.go#L33) when you attempt to use the Ping method?

My guess is that your account does not have permissions to check a bucket's ACL, which is what the [Ping method does](https://github.com/USACE/filestore/blob/main/s3store.go#L313).

Any ideas on a different AWS operation we could use for a Ping/to verify connection?

**Comment by ShaneMPutnam** [comment]
Yes, the error is "AccessDenied: Access Denied".

Maybe we could check a specific key using https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAcl.html or check the request from the bucket's ACL? It looks like the response code would be 403 for Access Denied and 400 if it failed out right.
